### ISSUE TITLE
运行 jupyter 时报错 "l.append("%s=%s" % (attr, `value`))"

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#103]
在制作 caffe image 时，通过 miniconda3-4.3.20 安装的 conda，再安装的 jupyter，在运行时报错如下：
```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 76, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/opt/conda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 16, in <module>
    from jupyter_client.session import Session
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/manager.py", line 32, in <module>
    from .session import Session
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/session.py", line 61, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/opt/conda/lib/python3.5/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "/opt/conda/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))

SyntaxError: invalid syntax
```

这里再补充说明下，Dockerfile 中有两次 pip install 操作，如下：
```
// 第一次是安装其他 python 依赖。
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -i http://pypi.doubanio.com/simple --trusted-host=pypi.doubanio.com  \
    ipython==5.5.0 \
    ipywidgets \
    ipykernel \
    h5py \
    jupyter \
    && \
    python -m ipykernel install

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -i http://pypi.doubanio.com/simple --trusted-host=pypi.doubanio.com  \
    ipython==5.5.0 \
    ipywidgets \
    ipykernel \
    h5py \
    jupyter

// 第二次是安装 caffe 依赖
RUN git clone -b ${CLONE_TAG} --depth 1 https://github.com/BVLC/caffe.git . && \
    pip install --upgrade pip && \
    cd python && for req in $(cat requirements.txt) pydot; do pip install $req; done && cd .. && \
    mkdir build && cd build && \
    cmake -DCPU_ONLY=1 .. && \
    make -j"$(nproc)"
```

测试了下只使用 python2 运行能成功，说明只在 python3 中存在该问题。查找了下 [issue-2344](https://github.com/jupyter/notebook/issues/2344)，说需要升级 python-dateutil，[python-dateutil](https://pypi.python.org/pypi/python-dateutil) 官方文档上看到 2.0 以上版本才支持 Python3。查看第一次 pip 已安装了 python-dateutil 已经为最新版了（2.6.1），感觉很奇怪。

后来一次重新build，在第二次的 pip 安装依赖时看到如下输出：
```
Installing collected packages: python-dateutil
  Found existing installation: python-dateutil 2.6.1
    Uninstalling python-dateutil-2.6.1:
      Successfully uninstalled python-dateutil-2.6.1
  Running setup.py install for python-dateutil: started
    Running setup.py install for python-dateutil: finished with status 'done'
Successfully installed python-dateutil-1.5
```

即新安装的 python-dateutil 2.6.1 被替换为  python-dateutil 1.5 了。查看 requirements.txt，有如下行：
```
python-dateutil>=1.4,<2
```

替换第二个 pip 操作，如下：
```
RUN cd python && \
    sed -i 's/python-dateutil>=1.4,<2/python-dateutil/' requirements.txt && \
    for req in $(cat requirements.txt) pydot; \
       do pip install --no-cache-dir -i http://pypi.doubanio.com/simple --trusted-host=pypi.doubanio.com $req; done && \
    cd .. && \
    mkdir build && cd build && \
    cmake -DCPU_ONLY=1 .. && \
    make -j"$(nproc)" 
```

build 后，运行 image 正常。

**Comment by mattshma** [comment]
Update

Python3 下安装的 caffe 在运行时报错：
```
ImportError: dynamic module does not define module export function (PyInit__caffe)
```

查看官网说明：
> Caffe’s Python interface works with Python 2.7. Python 3.3+ should work out of the box without protobuf support. For protobuf support please install protobuf 3.0 alpha (https://developers.google.com/protocol-buffers/). Earlier Pythons are your own adventure.

由于 Python3 不支持 protobuf，因此暂时仍只使用 Python 2.7。
