### ISSUE TITLE
HBase 1.0.0-cdh5.6.0  "AsyncProcess: Failed to get region location"

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#15]
## Detail
- HBase Version:  HBase 1.0.0-cdh5.6.0    
- Component/s: Thrift2
- Log:

```
16/04/13 10:17:33 ERROR client.AsyncProcess: Failed to get region location
java.io.IOException: hconnection-0x16188a0c to wgame_log is closed
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1116)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:369)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:320)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:206)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:183)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1513)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1119)
        at org.apache.hadoop.hbase.client.HTablePool$PooledHTable.put(HTablePool.java:449)
        at org.apache.hadoop.hbase.thrift2.ThriftHBaseServiceHandler.putMultiple(ThriftHBaseServiceHandler.java:271)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.hbase.thrift2.ThriftHBaseServiceHandler$THBaseServiceMetricsProxy.invoke(ThriftHBaseServiceHandler.java:104)
        at com.sun.proxy.$Proxy11.putMultiple(Unknown Source)
        at org.apache.hadoop.hbase.thrift2.generated.THBaseService$Processor$putMultiple.getResult(THBaseService.java:1486)
        at org.apache.hadoop.hbase.thrift2.generated.THBaseService$Processor$putMultiple.getResult(THBaseService.java:1470)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

- Patch: [HBASE-14196](https://issues.apache.org/jira/browse/HBASE-14196)

**Comment by mattshma** [comment]
- 卸载cloudera-manager-agent, cloudera-manage-server
```
# yum erase cloudera-manager-server
# yum erase cloudera-manager-agent 
```
- 修改`/etc/yum.repo.d/cdh5.repo`     
将cdh源指向5.7.0

- 重新安装cdh
- 安装后，hdfs服务正常，hbase需要修改meta数据。

**Comment by mattshma** [comment]
Update。

测试下来该问题没再产生，CDH5.7.0中HBase的版本为1.2.0。

**Comment by mattshma** [comment]
UPDATE：目前在CDH5.5.3上再现了这个问题，HBase版本为1.0.0。根据 #59 ，调整`hbase.ipc.client.connection.minIdleTimeBeforeClose`无效，客户端总是10分钟自动断开，考虑到`hbase.thrift.connection.max-idletime`默认为10分钟，于是调整该参数。

**Comment by mattshma** [comment]
见 [HBASE-14196](https://issues.apache.org/jira/browse/HBASE-14196) 和 [HBASE-14533](https://issues.apache.org/jira/browse/HBASE-14533)。
