### ISSUE TITLE
CDH新加主机时报错"AttributeError: 'NoneType' object has no attribute 'type'"

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#17]
ip为192.168.1.20，机器名为192-168-1-20，在添加进cdh时报错如下：
```
>>[20/Apr/2016 10:12:09 +0000] 19769 Monitor-HostMonitor network_interfaces WARNING Interface 'eth1' reported unknown duplex mode '255' 
>>[20/Apr/2016 10:12:09 +0000] 19769 MainThread agent ERROR Heartbeating to 192.168.1.10:7182 failed. 
>>Traceback (most recent call last): 
>> File "/usr/lib64/cmf/agent/src/cmf/agent.py", line 789, in send_heartbeat 
>> response = self.requestor.request('heartbeat', dict(request=heartbeat)) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/ipc.py", line 139, in request 
>> return self.issue_request(call_request, message_name, request_datum) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/ipc.py", line 255, in issue_request 
>> return self.read_call_response(message_name, buffer_decoder) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/ipc.py", line 235, in read_call_response 
>> raise self.read_error(writers_schema, readers_schema, decoder) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/ipc.py", line 244, in read_error 
>> return AvroRemoteException(datum_reader.read(decoder)) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/io.py", line 444, in read 
>> return self.read_data(self.writers_schema, self.readers_schema, decoder) 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/io.py", line 448, in read_data 
>> if not DatumReader.match_schemas(writers_schema, readers_schema): 
>> File "/usr/lib64/cmf/agent/build/env/lib/python2.6/site-packages/avro-1.6.3-py2.6.egg/avro/io.py", line 379, in match_schemas 
>> w_type = writers_schema.type 
>>AttributeError: 'NoneType' object has no attribute 'type' 
```

检验机器对比`/etc/sysconfig/network`和`hostname`和`/etc/hosts`均正常，且cloudera-scm-agent已启动成功。

最后解决问题的方法是修改了机器名，将机器名192-168-1-20改为hadoop01-001之类的即可。

奇怪的是这个hostname是什么规定？

**Comment by mattshma** [comment]
之前有次遇到这种报错的原因是agent端和server端 cm 版本不一致导致的。
