### ISSUE TITLE
flume closing file failed. Will retry again in 180 seconds.

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#22]
flume报错如下：
```
2016-04-27 23:59:59,171 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - org.apache.flume.sink.hdfs.BucketWriter.open(BucketWriter.java:261)] Creating hdfs://hadoop/user/hive/warehouse/wgame.db/log/tt=20160428/_10.2.1.12_1.1461772799103.cache
2016-04-28 00:46:06,376 (DataStreamer for file /user/hive/warehouse/wgame.db/log/tt=20160428/_10.2.1.12_1.1461772799103.cache block BP-1471860497-10.2.72.29-1421306158975:blk_1347593125_273921011) [WARN - org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1132)] Error Recovery for block BP-1471860497-10.2.72.29-1421306158975:blk_1347593125_273921011 in pipeline 10.2.96.4:50010, 10.2.96.40:50010, 10.2.96.30:50010: bad datanode 10.2.96.30:50010
2016-04-28 00:47:16,456 (DataStreamer for file /user/hive/warehouse/wgame.db/log/tt=20160428/_10.2.1.12_1.1461772799103.cache block BP-1471860497-10.2.72.29-1421306158975:blk_1347593125_273921011) [WARN - org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:627)] DataStreamer Exception
java.net.SocketTimeoutException: 70000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.2.1.12:36790 remote=/10.2.96.40:50010]
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:1986)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.transfer(DFSOutputStream.java:1063)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:1031)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1175)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.processDatanodeError(DFSOutputStream.java:924)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:486)
2016-04-28 00:47:17,510 (SinkRunner-PollingRunner-DefaultSinkProcessor) [WARN - org.apache.flume.sink.hdfs.BucketWriter.append(BucketWriter.java:599)] Caught IOException writing to HDFSWriter (70000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.2.1.12:36790 remote=/10.2.96.40:50010]). Closing file (hdfs://hadoop/user/hive/warehouse/wgame.db/log/tt=20160428/_10.2.1.12_1.1461772799103.cache) and rethrowing exception.
2016-04-28 00:47:17,511 (SinkRunner-PollingRunner-DefaultSinkProcessor) [WARN - org.apache.flume.sink.hdfs.BucketWriter.close(BucketWriter.java:410)] pre-close flush failed
java.net.SocketTimeoutException: 70000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/10.2.1.12:36790 remote=/10.2.96.40:50010]
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
        at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:1986)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.transfer(DFSOutputStream.java:1063)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:1031)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1175)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.processDatanodeError(DFSOutputStream.java:924)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:486)
```

**Comment by mattshma** [comment]
10.2.96.30节点因磁盘空间问题出现故障。又由于[FLUME-2357](https://issues.apache.org/jira/browse/FLUME-2357)和[FLUME-2586](https://issues.apache.org/jira/browse/FLUME-2586)导致一直重试。

解决方法：手动将文件名变更。
