### ISSUE TITLE
Region still in transition, waiting for it to become assigned

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#23]
在 #13 中已经遇到过这种情况，当时删除zookeeper中/hbase，重启集群再修复即可了。但这次这么做却失败了。

首先，hdfs fsck结果是正常的，hbase hbck报错为
```
java.io.IOException: Region {ENCODED => f1784add51a8b9e37ba197909484a1dd, NAME => 'snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.', STARTKEY => '2021310333_21652_1699741739', ENDKEY => '2021310334_11099_16997420249709551386'} failed to move out of transition within timeout 120000ms
	at org.apache.hadoop.hbase.util.HBaseFsckRepair.waitUntilAssigned(HBaseFsckRepair.java:149)
	at org.apache.hadoop.hbase.util.HBaseFsck.tryAssignmentRepair(HBaseFsck.java:2119)
	at org.apache.hadoop.hbase.util.HBaseFsck.checkRegionConsistency(HBaseFsck.java:2245)
	at org.apache.hadoop.hbase.util.HBaseFsck.access$1100(HBaseFsck.java:195)
	at org.apache.hadoop.hbase.util.HBaseFsck$CheckRegionConsistencyWorkItem.call(HBaseFsck.java:1892)
	at org.apache.hadoop.hbase.util.HBaseFsck$CheckRegionConsistencyWorkItem.call(HBaseFsck.java:1880)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/05/03 19:10:57 WARN util.HBaseFsck: Skip region 'snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.'
```

通过`locate_region`查看到出问题的几个region，查看该region server 的log，如下：
```
2016-05-03 19:08:57,606 INFO org.apache.hadoop.hbase.regionserver.RSRpcServices: Open snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:58,036 ERROR org.apache.hadoop.hbase.regionserver.HRegion: Could not initialize all stores for the region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:58,036 ERROR org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Failed open of region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd., starting to roll back the global memstore size.
2016-05-03 19:08:58,037 INFO org.apache.hadoop.hbase.coordination.ZkOpenRegionCoordination: Opening of region {ENCODED => f1784add51a8b9e37ba197909484a1dd, NAME => 'snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.', STARTKEY => '2021310333_21652_1699741739', ENDKEY => '2021310334_11099_16997420249709551386'} failed, transitioning from OPENING to FAILED_OPEN in ZK, expecting version 4
2016-05-03 19:08:58,703 INFO org.apache.hadoop.hbase.regionserver.RSRpcServices: Open snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:58,772 ERROR org.apache.hadoop.hbase.regionserver.HRegion: Could not initialize all stores for the region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:58,772 ERROR org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Failed open of region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd., starting to roll back the global memstore size.
2016-05-03 19:08:58,773 INFO org.apache.hadoop.hbase.coordination.ZkOpenRegionCoordination: Opening of region {ENCODED => f1784add51a8b9e37ba197909484a1dd, NAME => 'snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.', STARTKEY => '2021310333_21652_1699741739', ENDKEY => '2021310334_11099_16997420249709551386'} failed, transitioning from OPENING to FAILED_OPEN in ZK, expecting version 13
2016-05-03 19:08:59,334 INFO org.apache.hadoop.hbase.regionserver.RSRpcServices: Open snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:59,539 ERROR org.apache.hadoop.hbase.regionserver.HRegion: Could not initialize all stores for the region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.
2016-05-03 19:08:59,539 ERROR org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Failed open of region=snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd., starting to roll back the global memstore size.
2016-05-03 19:08:59,540 INFO org.apache.hadoop.hbase.coordination.ZkOpenRegionCoordination: Opening of region {ENCODED => f1784add51a8b9e37ba197909484a1dd, NAME => 'snsgz_log,2021310333_21652_1699741739,1462273604814.f1784add51a8b9e37ba197909484a1dd.', STARTKEY => '2021310333_21652_1699741739', ENDKEY => '2021310334_11099_16997420249709551386'} failed, transitioning from OPENING to FAILED_OPEN in ZK, expecting version 28
```

问题出现目录不存在。

**Comment by mattshma** [comment]
解决方法：进入hbase shell中，执行命令:`disable 'snsgz_log'`后，再次`hbase hbck -repair`，修复成功。再执行`enable 'snsgz_log'`，再次`hbase hbck -repair`，修复成功。最后`hbase hbck`，状态ok。

很奇怪为什么会这样会修复？或者只需要重新加载下表就ok？加载表的过程中会发生什么？

**Comment by mattshma** [comment]
初步猜测重新disable再enable的过程中，该表的各regionserver会重新向hmaster汇报该表状态。后续需验证。

**Comment by mattshma** [comment]
再次遇到这个问题，log同之前一样：
```
2016-07-29 14:49:52,211 INFO org.apache.hadoop.hbase.regionserver.HRegionServer: Open sn_log,2021310534_10608_16981548956709551452,1469630166524.6b3711cb0dfd408711ddbff640d06172.
2016-07-29 14:49:52,234 INFO org.apache.hadoop.hbase.regionserver.compactions.CompactionConfiguration: size [134217728, 9223372036854775807); files [3, 10); ratio 1.200000; off-peak ratio 5.000000; throttle point 2684354560; delete expired; major period 604800000, major jitter 0.500000
2016-07-29 14:49:52,332 ERROR org.apache.hadoop.hbase.regionserver.HRegion: Could not initialize all stores for the region=sn_log,2021310534_10608_16981548956709551452,1469630166524.6b3711cb0dfd408711ddbff640d06172.
2016-07-29 14:49:52,332 ERROR org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Failed open of region=sn_log,2021310534_10608_16981548956709551452,1469630166524.6b3711cb0dfd408711ddbff640d06172., starting to roll back the global memstore size.
java.io.IOException: java.io.IOException: java.io.FileNotFoundException: File does not exist: /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/info/18a0bc39078e4ca3b5c52e8e0a160193
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:65)
        at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:55)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsUpdateTimes(FSNamesystem.java:1726)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsInt(FSNamesystem.java:1669)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1649)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1621)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:482)
```
文件不存在，查看`hbase:meta`，该region这行记录存在，查看hdfs里中该表的这个region：
```
# sudo -u hbase hdfs dfs -ls /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f
Found 4 items
-rwxr-xr-x   3 hbase hbase        107 2016-04-07 20:02 /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/.regioninfo
drwxr-xr-x   - hbase hbase          0 2016-07-29 19:55 /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/.tmp
drwxr-xr-x   - hbase hbase          0 2016-07-29 19:55 /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/info
drwxr-xr-x   - hbase hbase          0 2016-07-28 07:39 /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/recovered.edits
# sudo -u hbase hdfs dfs -ls /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/info
ls: `/hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f/info': No such file or directory
```
在hdfs上删除该region并重新`-repair`即可：
```
# sudo -u hbase hdfs dfs -rmr /hbase/data/default/sn_log/745601ca7641ffb4fb07014d1558471f
```

注意，即使删除zk信息并重启，通过`hbase org.apache.hadoop.hbase.util.hbck.OfflineMetaRepair`重建META表，仍无法解决该问题，只能通过删除hdfs上该不存在的region解决。

**Comment by mattshma** [comment]
#49 。
