### ISSUE TITLE
hadoop不同版本distcp时报错：Couldn't run retriable-command

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#33]
报错如下：
```
Error: java.io.IOException: File copy failed: 
webhdfs://10.2.72.29:50070/hbase/data/default/snsgz_log/00115558db32e80778db35f0f096e126/.regioninfo --> 
webhdfs://10.6.24.105:50070/hbase/data/default/snsgz_log/00115558db32e80778db35f0f096e126/.regio
ninfo at org.apache.hadoop.tools.mapred.CopyMapper.copyFileWithRetry(CopyMapper.java:284) at 
org.apache.hadoop.tools.mapred.CopyMapper.map(CopyMapper.java:252) at 
org.apache.hadoop.tools.mapred.CopyMapper.map(CopyMapper.java:50) at 
org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145) at 
org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) at 
org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) at 
org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164) at 
java.security.AccessController.doPrivileged(Native Method) at 
javax.security.auth.Subject.doAs(Subject.java:415) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693) at 
org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158) Caused by: java.io.IOException: 
Couldn't run retriable-command: Copying 
webhdfs://10.2.72.29:50070/hbase/data/default/snsgz_log/00115558db32e80778db35f0f096e126/.region
info to 
webhdfs://10.6.24.105:50070/hbase/data/default/snsgz_log/00115558db32e80778db35f0f096e126/.regio
ninfo at org.apache.hadoop.tools.util.RetriableCommand.execute(RetriableCommand.java:101) at 
org.apache.hadoop.tools.mapred.CopyMapper.copyFileWithRetry(CopyMapper.java:280) ... 10 more 
Caused by: org.apache.hadoop.tools.mapred.RetriableFileCopyCommand$CopyReadException: 
java.net.UnknownHostException: DataNode0008:50075: DataNode0008 at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.readBytes(RetriableFileCopyCommand.java:289) at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.copyBytes(RetriableFileCopyCommand.java:249) at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.copyToFile(RetriableFileCopyCommand.java:184) at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.doCopy(RetriableFileCopyCommand.java:124) at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.doExecute(RetriableFileCopyCommand.java:100) at org.apache.hadoop.tools.util.RetriableCommand.execute(RetriableCommand.java:87) ... 11 
more Caused by: java.net.UnknownHostException: DataNode0008:50075: DataNode0008 at 
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at 
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) at 
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:526) at 
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.runWithRetry(WebHdfsFileSystem.java:643) at 
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.access$100(WebHdfsFileSystem.java:471) at 
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner$1.run(WebHdfsFileSystem.java:501) at java.security.AccessController.doPrivileged(Native Method) at 
javax.security.auth.Subject.doAs(Subject.java:415) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693) at 
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.run(WebHdfsFileSystem.java:497) at
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$ReadRunner.read(WebHdfsFileSystem.java:1663) at 
org.apache.hadoop.hdfs.web.WebHdfsFileSystem$WebHdfsInputStream.read(WebHdfsFileSystem.java:
1524) at java.io.DataInputStream.read(DataInputStream.java:100) at org.apache.hadoop.tools.util.ThrottledInputStream.read(ThrottledInputStream.java:80) at 
org.apache.hadoop.tools.mapred.RetriableFileCopyCommand.readBytes(RetriableFileCopyCommand.java:284) ... 16 more

```

**Comment by mattshma** [comment]
通过报错可找到相关问题，checksum不同会导致该问题，/etc/hosts配置不对也会导致该问题。
