### ISSUE TITLE
Got error for OP_READ_BLOCK

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#48]
HBase在做hbck操作时，报错如下：
```
16/06/22 11:37:27 WARN hdfs.BlockReaderFactory: I/O error constructing remote block reader.
java.io.IOException: Got error for OP_READ_BLOCK, self=/10.2.96.3:48237, remote=/10.2.96.4:50010, for file /hbase/data/default/snsgz_log/b6695f11503abf53871e022fe5b5d95c/.regioninfo, for pool BP-1471860497-10.2.72.29-1421306158975 block 1110841200_37103202
	at org.apache.hadoop.hdfs.RemoteBlockReader2.checkSuccess(RemoteBlockReader2.java:432)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:397)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:786)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:665)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:325)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:566)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:789)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:836)
	at java.io.DataInputStream.read(DataInputStream.java:100)
	at org.apache.hadoop.hbase.HRegionInfo.parseFrom(HRegionInfo.java:1090)
	at org.apache.hadoop.hbase.regionserver.HRegionFileSystem.loadRegionInfoFileContent(HRegionFileSystem.java:714)
	at org.apache.hadoop.hbase.util.HBaseFsck.loadHdfsRegioninfo(HBaseFsck.java:875)
	at org.apache.hadoop.hbase.util.HBaseFsck.access$2300(HBaseFsck.java:169)
	at org.apache.hadoop.hbase.util.HBaseFsck$WorkItemHdfsRegionInfo.call(HBaseFsck.java:3501)
	at org.apache.hadoop.hbase.util.HBaseFsck$WorkItemHdfsRegionInfo.call(HBaseFsck.java:3485)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/06/22 11:37:27 WARN hdfs.DFSClient: Failed to connect to /10.2.96.4:50010 for block, add to deadNodes and continue. java.io.IOException: Got error for OP_READ_BLOCK, self=/10.2.96.3:48237, remote=/10.2.96.4:50010, for file /hbase/data/default/snsgz_log/b6695f11503abf53871e022fe5b5d95c/.regioninfo, for pool BP-1471860497-10.2.72.29-1421306158975 block 1110841200_37103202
```

**Comment by yongdong7** [comment]
遇到完全一致的错误，hbase版本号1.2.0-cdh5
进一步确认对应block是前几天已被删除的（在你的例子中是 block 1110841200_37103202）
怀疑可能的问题是hbase哪里存在缓存机制，在我的例子中前几天手动运行过hdfs balance动作。

**Comment by yongdong7** [comment]
2024-01-26 09:37:22,178 WARN org.apache.hadoop.hdfs.BlockReaderFactory: I/O error constructing remote block reader.
java.io.IOException: Got error for OP_READ_BLOCK, status=ERROR, self=/10.1.4.43:59726, remote=/10.1.4.49:50010, for file /hbase/data/ns1/tablename1/eba7f3ea74b6009b7906979f60dfc9fd/info/7f79b6ad52774d88a97a27fae306c4fb, for pool BP-307073671-10.1.4.27-1672726378357 block 1130451443_56711443
	at org.apache.hadoop.hdfs.RemoteBlockReader2.checkSuccess(RemoteBlockReader2.java:467)
	at org.apache.hadoop.hdfs.RemoteBlockReader2.newBlockReader(RemoteBlockReader2.java:432)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReader(BlockReaderFactory.java:890)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:768)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:377)
	at org.apache.hadoop.hdfs.DFSInputStream.actualGetFromOneDataNode(DFSInputStream.java:1220)
	at org.apache.hadoop.hdfs.DFSInputStream.fetchBlockByteRange(DFSInputStream.java:1160)
	at org.apache.hadoop.hdfs.DFSInputStream.pread(DFSInputStream.java:1534)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:1493)
	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:92)
	at org.apache.hadoop.hbase.io.hfile.HFileBlock.positionalReadWithExtra(HFileBlock.java:757)
	at org.apache.hadoop.hbase.io.hfile.HFileBlock$AbstractFSReader.readAtOffset(HFileBlock.java:1463)
	at org.apache.hadoop.hbase.io.hfile.HFileBlock$FSReaderImpl.readBlockDataInternal(HFileBlock.java:1688)
	at org.apache.hadoop.hbase.io.hfile.HFileBlock$FSReaderImpl.readBlockData(HFileBlock.java:1548)
	at org.apache.hadoop.hbase.io.hfile.HFileReaderV2.readBlock(HFileReaderV2.java:446)
	at org.apache.hadoop.hbase.util.CompoundBloomFilter.contains(CompoundBloomFilter.java:100)
	at org.apache.hadoop.hbase.regionserver.StoreFile$Reader.passesGeneralBloomFilter(StoreFile.java:1387)
	at org.apache.hadoop.hbase.regionserver.StoreFile$Reader.passesBloomFilter(StoreFile.java:1251)
	at org.apache.hadoop.hbase.regionserver.StoreFileScanner.shouldUseScanner(StoreFileScanner.java:472)
	at org.apache.hadoop.hbase.regionserver.StoreScanner.selectScannersFrom(StoreScanner.java:400)
	at org.apache.hadoop.hbase.regionserver.StoreScanner.getScannersNoCompaction(StoreScanner.java:319)
	at org.apache.hadoop.hbase.regionserver.StoreScanner.<init>(StoreScanner.java:193)
	at org.apache.hadoop.hbase.regionserver.HStore.createScanner(HStore.java:2123)
	at org.apache.hadoop.hbase.regionserver.HStore.getScanner(HStore.java:2113)
	at org.apache.hadoop.hbase.regionserver.HRegion$RegionScannerImpl.<init>(HRegion.java:5732)
	at org.apache.hadoop.hbase.regionserver.HRegion.instantiateRegionScanner(HRegion.java:2637)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2623)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2604)
	at org.apache.hadoop.hbase.regionserver.HRegion.get(HRegion.java:7022)
	at org.apache.hadoop.hbase.regionserver.HRegion.get(HRegion.java:6981)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2027)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:33644)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2191)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
2024-01-26 09:37:22,178 WARN org.apache.hadoop.hdfs.DFSClient: Connection failure: Failed to connect to /10.1.4.49:50010 for file /hbase/data/ns1/tablename1/eba7f3ea74b6009b7906979f60dfc9fd/info/7f79b6ad52774d88a97a27fae306c4fb for block BP-307073671-10.1.4.27-1672726378357:blk_1130451443_56711443
