### ISSUE TITLE
Regions in Transition

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#49]
HBase报错如下：
![111111111111](https://cloud.githubusercontent.com/assets/3884630/16263498/3ac595a2-38a7-11e6-823d-23297a7be46a.jpg)

查看该刚机器关于该region的日志:
```
2016-06-22 18:22:27,844 INFO org.apache.hadoop.hbase.regionserver.HRegionServer: Open snsgz_log,2021310388_19252_16992227940709551557,1466578007529.3c5fdb81ca9aa4fa7a17ef5b00ae67fc.
2016-06-22 18:22:28,075 ERROR org.apache.hadoop.hbase.regionserver.HRegion: Could not initialize all stores for the region=snsgz_log,2021310388_19252_16992227940709551557,1466578007529.3c5fdb81ca9aa4fa7a17ef5b00ae67fc.
2016-06-22 18:22:28,075 ERROR org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Failed open of region=snsgz_log,2021310388_19252_16992227940709551557,1466578007529.3c5fdb81ca9aa4fa7a17ef5b00ae67fc., starting to roll back the global memstore size.
2016-06-22 18:22:28,084 INFO org.apache.hadoop.hbase.regionserver.handler.OpenRegionHandler: Opening of region {ENCODED => 3c5fdb81ca9aa4fa7a17ef5b00ae67fc, NAME => 'snsgz_log,2021310388_19252_16992227940709551557,1466578007529.3c5fdb81ca9aa4fa7a17ef5b00ae67fc.', STARTKEY => '2021310388_19252_16992227940709551557', ENDKEY => '2021310388_21716_16992190057709551597'} failed, transitioning from OPENING to FAILED_OPEN in ZK, expecting version 190
```

**Comment by mattshma** [comment]
直接在hbase shell中assign该region会失败。解决方法目前删除zookeeper中`/hbase`的znode，然后重启集群。

**Comment by mattshma** [comment]
再次报这个问题，影响是hbase无法写。即使删除zookeeper的`/hbase`，该问题仍存在。通过`hbase org.apache.hadoop.hbase.util.hbck.OfflineMetaRepair`修改也没用。然后通过`hbase org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles pathToHFiles tableName
`一直提示表不可用，但表正常。

再看相关regionlog，报错如下：
```
java.io.IOException: java.io.IOException: org.apache.hadoop.hbase.io.hfile.CorruptHFileException: Problem reading HFile Trailer from file hdfs://hadoop/hbase/data/default/xxxxxxx/171d5cde7b53f0b258b223d942eadc79/info/f8e266eadab14df790d52f713a6ad837
        at org.apache.hadoop.hbase.regionserver.HRegion.initializeRegionStores(HRegion.java:804)
        at org.apache.hadoop.hbase.regionserver.HRegion.initializeRegionInternals(HRegion.java:714)
..
Caused by: org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1471860497-10.2.72.29-1421306158975:blk_1420918210_347279307 file=/hbase/data/default/xxxx/bb66aff9c3cbcef2fb1a159fd4fd45e0/info/8edacde37ca0473781ceedebad511a82
...

Caused by: org.apache.hadoop.hbase.io.hfile.CorruptHFileException: Problem reading HFile Trailer from file hdfs://hadoop/hbase/data/default/xxxxx/0cacda1528ed014b420b9b13d12b8b4/info/8b23f292d924469c93ac9b0a1e94c54e
        at org.apache.hadoop.hbase.io.hfile.HFile.pickReaderVersion(HFile.java:552)
        at org.apache.hadoop.hbase.io.hfile.HFile.createReader(HFile.java:580)
        at org.apache.hadoop.hbase.regionserver.StoreFile$Reader.<init>(StoreFile.java:1013)
        at org.apache.hadoop.hbase.regionserver.StoreFileInfo.open(StoreFileInfo.java:211)
        at org.apache.hadoop.hbase.regionserver.StoreFile.open(StoreFile.java:344)
        at org.apache.hadoop.hbase.regionserver.StoreFile.createReader(StoreFile.java:439)
        at org.apache.hadoop.hbase.regionserver.HStore.createStoreFileAndReader(HStore.java:551)
        at org.apache.hadoop.hbase.regionserver.HStore.access$000(HStore.java:118)
        at org.apache.hadoop.hbase.regionserver.HStore$1.call(HStore.java:500)
        at org.apache.hadoop.hbase.regionserver.HStore$1.call(HStore.java:497)
        ... 6 more
Caused by: java.io.IOException: Invalid HFile block magic: \x00\x00\x00\x00\x00\x00\x00\x00
        at org.apache.hadoop.hbase.io.hfile.BlockType.parse(BlockType.java:154)
        at org.apache.hadoop.hbase.io.hfile.BlockType.read(BlockType.java:165)
        at org.apache.hadoop.hbase.io.hfile.HFileBlock.<init>(HFileBlock.java:239)
        at org.apache.hadoop.hbase.io.hfile.HFileBlock$FSReaderV2.readBlockDataInternal(HFileBlock.java:1486)
        at org.apache.hadoop.hbase.io.hfile.HFileBlock$FSReaderV2.readBlockData(HFileBlock.java:1314)
        at org.apache.hadoop.hbase.io.hfile.HFileBlock$AbstractFSReader$1.nextBlock(HFileBlock.java:1151)
        at org.apache.hadoop.hbase.io.hfile.HFileBlock$AbstractFSReader$1.nextBlockWithBlockType(HFileBlock.java:1159)
        at org.apache.hadoop.hbase.io.hfile.HFileReaderV2.<init>(HFileReaderV2.java:144)
        at org.apache.hadoop.hbase.io.hfile.HFile.pickReaderVersion(HFile.java:540)
        ... 15 more
```
