### ISSUE TITLE
Failed getting lock in batch put, row=xxx

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#56]
hbase报错如下：
```
3:00:16.273 PM	WARN	org.apache.hadoop.hbase.regionserver.HRegion	
Failed getting lock in batch put, row=2033311029_13849_16976797975709551613
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion sn,2033311029_12398_16978242070709551595,1469210736441.b972aa84d9f1b8724257e2a473a80d5d., startKey='2033311029_12398_16978242070709551595', getEndKey()='2033311029_13431_1698621146470955151', row='2033311029_13849_16976797975709551613'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3421)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLock(HRegion.java:3439)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2382)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2249)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2201)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2205)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.doBatchOp(HRegionServer.java:4253)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.doNonAtomicRegionMutation(HRegionServer.java:3469)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.multi(HRegionServer.java:3359)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:29503)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2012)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:98)
	at org.apache.hadoop.hbase.ipc.SimpleRpcScheduler.consumerLoop(SimpleRpcScheduler.java:160)
	at org.apache.hadoop.hbase.ipc.SimpleRpcScheduler.access$000(SimpleRpcScheduler.java:38)
	at org.apache.hadoop.hbase.ipc.SimpleRpcScheduler$1.run(SimpleRpcScheduler.java:110)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattshma** [comment]
查看rowkey，发现其在Region的Startkey和endkey外面。本想通过`merge_region`来合并相邻region。但又发现此rowkey在两个region中间。于是重新生成hbase:meta文件，注意，在重新生成的过程，对于start key冲突的region，要先删除。
