### ISSUE TITLE
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 112881916 larger than 104857600)

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#62]
通过flume向kafka发送数据。配置flume的batchsize为50万，一段时间后，flume报错如下：
```
Sep 6, 9:54:58.062 AM	ERROR	com.uuzu.flume.sink.kafkasink.KafkaSink	
Failed to publish events
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
	at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	at kafka.producer.Producer.send(Producer.scala:76)
	at kafka.javaapi.producer.Producer.send(Producer.scala:42)
	at com.uuzu.flume.sink.kafkasink.KafkaSink.process(KafkaSink.java:140)
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
	at java.lang.Thread.run(Thread.java:745)
```

查看kafka log，报错如下：
```
Sep 6, 9:55:10.094 AM	WARN	org.apache.kafka.common.network.Selector	
Unexpected error from /10.6.25.161; closing connection
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 112881916 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:91)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:153)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:134)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:323)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:283)
	at kafka.network.Processor.run(SocketServer.scala:413)
	at java.lang.Thread.run(Thread.java:745)
```

kafka默认配置一次socket请求最多处理100MB数据，属性为`socket.request.max.bytes`。默认情况下该值已能满足大部分需求。故将flume sink的batchsize调小到100000，即平均一个message最大为1KB，一次请求这处理10万个这个的message。重新加载flume。问题解决。

**Comment by AKR2015** [comment]
hi, were you able to resolve this issue, I am also facing the issue.

**Comment by Ritesh-Sharma** [comment]
@mattshma : Kindly mention the solution , which worked for you .

**Comment by mattshma** [comment]
@AKR2015 @Ritesh-Sharma:    
My scenario is used flume source send data to Kafka, for this issue, I just decreased the `batchSize` which is a [kafka sink propertity](https://flume.apache.org/FlumeUserGuide.html#kafka-sink), then refreshed flume config. `batchSize` property is deprecated now and called `flumeBatchSize`.
