### ISSUE TITLE
Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#63]
flume写hdfs突然报错如下：
```
2016-09-08 12:06:21,473 ERROR com.zu.flume.sink.hdfssink.AbstractHDFSWriter: Unexpected error while checking replication factor
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.zu.flume.sink.hdfssink.AbstractHDFSWriter.getNumCurrentReplicas(Unknown Source)
        at com.zu.flume.sink.hdfssink.AbstractHDFSWriter.isUnderReplicated(Unknown Source)
        at com.zu.flume.sink.hdfssink.BucketWriter.shouldRotate(Unknown Source)
        at com.zu.flume.sink.hdfssink.BucketWriter.append(Unknown Source)
        at com.zu.flume.sink.hdfssink.HDFSEventSink.process(Unknown Source)
        at org.apache.flume.sink.FailoverSinkProcessor.process(FailoverSinkProcessor.java:182)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[10.6.25.184:50010,DS-a67e1753-7160-4c87-8a87-330732f6ac30,DISK], DatanodeInfoWithStorage[10.6.25.189:50010,DS-f42cdbb3-7981-4630-8b98-0ac04bdf92a2,DISK]], original=[DatanodeInfoWithStorage[10.6.25.184:50010,DS-a67e1753-7160-4c87-8a87-330732f6ac30,DISK], DatanodeInfoWithStorage[10.6.25.189:50010,DS-f42cdbb3-7981-4630-8b98-0ac04bdf92a2,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.findNewDatanode(DFSOutputStream.java:1162)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.addDatanode2ExistingPipeline(DFSOutputStream.java:1228)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.setupPipelineForAppendOrRecovery(DFSOutputStream.java:1375)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.processDatanodeError(DFSOutputStream.java:1119)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:622)
2016-09-08 12:06:21,473 WARN com.zu.flume.sink.hdfssink.BucketWriter: Caught IOException writing to HDFSWriter (Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[DatanodeInfoWithStorage[10.6.25.184:50010,DS-a67e1753-7160-4c87-8a87-330732f6ac30,DISK], DatanodeInfoWithStorage[10.6.25.189:50010,DS-f42cdbb3-7981-4630-8b98-0ac04bdf92a2,DISK]], original=[DatanodeInfoWithStorage[10.6.25.184:50010,DS-a67e1753-7160-4c87-8a87-330732f6ac30,DISK], DatanodeInfoWithStorage[10.6.25.189:50010,DS-f42cdbb3-7981-4630-8b98-0ac04bdf92a2,DISK]]). The current failed datanode replacement policy is DEFAULT, and a client may configure this via 'dfs.client.block.write.replace-datanode-on-failure.policy' in its configuration.). Closing file (hdfs://hadoop/user/hive/warehouse/gamelog_raw.db/log_rslvup/game_id=152/ds=20160908/log3_sdk_data) and rethrowing exception.
2016-09-08 12:06:21,474 WARN com.zu.flume.sink.hdfssink.BucketWriter: Caught IOException while closing file (hdfs://hadoop/user/hive/warehouse/gamelog_raw.db/log_rslvup/game_id=152/ds=20160908/log3_sdk_data). Exception follows.
```

根据[HDFS-4600](https://issues.apache.org/jira/browse/HDFS-4600)和[hdfs-default.xml](https://hadoop.apache.org/docs/r2.6.0/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml)说明，出现该问题的原因是磁盘或网络异常，若节点数较多的话，默认配置即可。

检查磁盘和网络均正常。修改flume配置，重新加载即可。

**Comment by Winniehong** [comment]
请问修改flume的什么配置呢？我也遇到这个问题。

**Comment by mattshma** [comment]
@Winniehong ，若相关的几个dn服务正常，说明该问题可能由网络波动等引起，此时reload下flume的配置即可。若使用CDH，可点击`Update Config`进行reload。
