### ISSUE TITLE
hbase balance一直开启，导致服务异常

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#77]
这里说下表象：线上服务一直正常。由于region分布不太均匀，执行`balance_switch true`，一段时间后，region分布均匀。一周后，业务方反馈写hbase很多失败。查看thrift2 log，发现日志如下：
```
 on bd151-021.yzdns.com,60020,1477558578001, tracking started Mon Dec 26 16:24:15 CST 2016; not retrying 12 - final failure
#724695600, table=s_log, attempt=1/35 failed=12ops, last exception: org.apache.hadoop.hbase.exceptions.FailedSanityCheckException: org.apache.hadoop.hbase.exceptions.FailedSanityCheckException: Requested row out of range for doMiniBatchMutation on HRegion s_log,2033311555_17063_16965762813709551561,1481453842286.dea80ecb7d2f33a61a9db6620351572e., startKey='2033311555_17063_16965762813709551561', getEndKey()='2033311558_15385_16966470416709551522', row='2033311565_10133_16964040627709551615'
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:763)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:713)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:2148)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:33656)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2170)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:109)
        at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:133)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:108)
        at java.lang.Thread.run(Thread.java:745)
```

使用hbase hbck发现确实存在inconsistency的问题，执行repair，一直有1--3个inconsistency不能修复，查看HMaster日志，发现balancer一直进行，执行``balance_switch false`后，再次repair，修复成功。

这里有个问题，执行长时间的balance会导致inconsistency不一致的问题？先占个坑，后续有时间再测试。

**Comment by Jiangze-Yu** [comment]
想请教下，我们的集群再hbase shell里面执行balance_switch true之后，负载均衡并没有起作用，执行balance_switch status发现负载均衡自动关闭了，想请教下执行负载均衡指令之前是有什么其他操作吗？

**Comment by bblzjp** [comment]
@Jiangze-Yu 开启balance_switch true 后 还是负载不均衡  有什么解决办法么。我也遇到这个问题了
