### ISSUE TITLE
客户端请求返回值太大导致 RegionServer  OOM，集群异常

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#88]
### 背景
HBase Version：0.94

HBase 集群响应变慢。检查集群发现部分 Region 未能加载。

### 处理过程
分析请求情况，发现一台 RegionServer 请求量一直为 0，查看该 RegionServer 的 hbase.log 日志，报错 Region 不能加载。查看 hbase.out 日志，提示 OOM。再次查看 hbase.log 相关 Log，如下：
```
2017-04-13 13:41:14,367 WARN org.apache.hadoop.ipc.HBaseServer: (operationTooLarge): {"processingtimems":21419,"timeRange":[0,9223372036854775807],"client":"10.18.10
.19:50384","starttimems":1492062052891,"queuetimems":0,"class":"HRegionServer","responsesize":1651674019,"method":"get","cacheBlocks":true,"totalColumns":1,"table":"
mxxx","families":{"f":["ALL"]},"maxVersions":1,"row":"103-2321-111"}
2017-04-13 13:45:21,663 DEBUG org.apache.hadoop.hbase.io.hfile.LruBlockCache: Stats: total=22.81 GB, free=4.77 GB, max=27.58 GB, blocks=432774, accesses=44702445, hi
ts=42838222, hitRatio=95.83%, , cachingAccesses=43278515, cachingHits=42541936, cachingHitsRatio=98.30%, , evictions=0, evicted=302904, evictedPerRun=Infinity
2017-04-13 13:45:21,664 WARN org.apache.hadoop.hbase.util.Sleeper: We slept 247188ms instead of 3000ms, this is likely due to a long garbage collecting pause and it'
s usually bad, see http://hbase.apache.org/book.html#trouble.rs.runtime.zkexpired
2017-04-13 13:45:21,664 WARN org.apache.hadoop.hbase.util.Sleeper: We slept 247700ms instead of 10000ms, this is likely due to a long garbage collecting pause and it
's usually bad, see http://hbase.apache.org/book.html#trouble.rs.runtime.zkexpired
2017-04-13 13:46:17,535 WARN org.apache.hadoop.hdfs.DFSClient: DataStreamer Exception
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
        at org.apache.hadoop.net.SocketOutputStream$Writer.performIO(SocketOutputStream.java:62)
        at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:143)
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at org.apache.hadoop.net.SocketOutputStream.write(SocketOutputStream.java:114)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at org.apache.hadoop.hdfs.DFSOutputStream$Packet.writeTo(DFSOutputStream.java:265)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:542)
2017-04-13 13:46:17,535 FATAL org.apache.hadoop.hbase.regionserver.HRegionServer: Run out of memory; HRegionServer will abort itself immediately
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:331)
        at org.apache.hadoop.hbase.util.ByteBufferOutputStream.checkSizeAndGrow(ByteBufferOutputStream.java:69)
        at org.apache.hadoop.hbase.util.ByteBufferOutputStream.write(ByteBufferOutputStream.java:107)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
```

分析以上 log，知客户端请求量过大，导致 RegionServer OOM，因此整个过程大致为：客户端 get 很大的数据，导致 RegionServer 挂掉，该 RegionServer 上的 Region 未能分配出去，使部分表缺数据，同时 hang 住 HMaster 请求，整个集群响应变慢。

### HBase Slow Query
查看 [Slow Query 文档](http://hbase.apache.org/0.94/book/ops.monitoring.html)，知有两种情况会导致 Slow Query：响应时间长和响应返回量过大，这分别对应四种标记(tag)：`responseTooSlow`, `responseTooLarge`, `operationTooSlow`, `operationTooLarge`，这两种情况对应参数为 `hbase.ipc.warn.response.time`(单位 ms，默认 10s，设置为 -1 表示禁止以时间表明慢查询) 和 `hbase.ipc.warn.response.size`(单位 byte，默认 100 mb，设置为 -1 表示禁止以返回量表明慢查询)。

如果是客户端操作的  Put, Get, 或 Delete 导致的慢查询，则 LOG 中会以 `operationTooSlow`/`operationTooLarge` 来标记，否则以 `responseTooSlow`/`responseTooLarge` 标记。

### 解决方案
由于是客户端请求结果太大导致，所以需要业务方配合修改业务逻辑，或限制请求大小，如设置 `setBatch()` 等

**Comment by mattshma** [comment]
可以通过打 patch，用 `hbase.client.scanner.max.result.size` 来限制响应大小，而非 setCache。如下：
- [HBASE-13262](https://issues.apache.org/jira/browse/HBASE-13262)
- [HBASE-13292](https://issues.apache.org/jira/browse/HBASE-13292
- [HBASE-13362](https://issues.apache.org/jira/browse/HBASE-13362)
- [HBASE-13527](https://issues.apache.org/jira/browse/HBASE-13527)
