### ISSUE TITLE
cloudera manager 5.12.0 agent启动后自动停止问题

### ISSUE THREAD

**Issue by leiyazhen** [mattshma/bigdata#93]
[09/Aug/2017 01:55:24 +0000] 15125 MainThread agent        INFO     SCM Agent Version: 5.12.0
[09/Aug/2017 01:55:24 +0000] 15125 MainThread agent        INFO     Agent Protocol Version: 4
[09/Aug/2017 01:55:24 +0000] 15125 MainThread agent        INFO     Using Host ID: c10db648-662d-49d0-b6bd-f492ba7e627f
[09/Aug/2017 01:55:24 +0000] 15125 MainThread agent        INFO     Using directory: /opt/cm-5.12.0/run/cloudera-scm-agent
[09/Aug/2017 01:55:26 +0000] 15125 MainThread cgroups      INFO     Found cgroups subsystem: memory
[09/Aug/2017 01:55:26 +0000] 15125 MainThread cgroups      INFO     Found cgroups subsystem: blkio
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Setting up supervisord event monitor.
[09/Aug/2017 01:55:26 +0000] 15125 MainThread filesystem_map INFO     Monitored nodev filesystem types: ['nfs', 'nfs4', 'tmpfs']
[09/Aug/2017 01:55:26 +0000] 15125 MainThread filesystem_map INFO     Using timeout of 2.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread filesystem_map INFO     Using join timeout of 0.100000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread filesystem_map INFO     Using tolerance of 60.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread filesystem_map INFO     Local filesystem types whitelist: ['ext2', 'ext3', 'ext4', 'xfs']
[09/Aug/2017 01:55:26 +0000] 15125 MainThread kt_renewer   INFO     Agent wide credential cache set to /opt/cm-5.12.0/run/cloudera-scm-agent/krb5cc_cm_agent_0
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Using metrics_url_timeout_seconds of 30.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Using task_metrics_timeout_seconds of 5.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Using max_collection_wait_seconds of 10.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread ntp_monitor  INFO     Using timeout of 2.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread dns_names    INFO     Using timeout of 30.000000
[09/Aug/2017 01:55:26 +0000] 15125 MainThread __init__     INFO     Created DNS monitor.
[09/Aug/2017 01:55:26 +0000] 15125 MainThread stacks_collection_manager INFO     Using max_uncompressed_file_size_bytes: 5242880
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Re-using pre-existing directory: /opt/cm-5.12.0/run/cloudera-scm-agent/process
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Re-using pre-existing directory: /opt/cm-5.12.0/run/cloudera-scm-agent/supervisor
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        WARNING  Expected user cloudera-scm for /opt/cm-5.12.0/run/cloudera-scm-agent/flood but was root
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        WARNING  Expected group cloudera-scm for /opt/cm-5.12.0/run/cloudera-scm-agent/flood but was root
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        WARNING  Expected mode 0751 for /opt/cm-5.12.0/run/cloudera-scm-agent/flood but was 0755
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Re-using pre-existing directory: /opt/cm-5.12.0/run/cloudera-scm-agent/flood
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        INFO     Re-using pre-existing directory: /opt/cm-5.12.0/run/cloudera-scm-agent/supervisor/include
[09/Aug/2017 01:55:26 +0000] 15125 MainThread agent        ERROR    Failed to connect to previous supervisor.
Traceback (most recent call last):
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.12.0-py2.7.egg/cmf/agent.py", line 2109, in find_or_start_supervisor
    self.configure_supervisor_clients()
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.12.0-py2.7.egg/cmf/agent.py", line 2290, in configure_supervisor_clients
    supervisor_options.realize(args=["-c", os.path.join(self.supervisor_dir, "supervisord.conf")])
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/options.py", line 1599, in realize
    Options.realize(self, *arg, **kw)
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/options.py", line 333, in realize
    self.process_config()
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/options.py", line 341, in process_config
    self.process_config_file(do_usage)
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/options.py", line 376, in process_config_file
    self.usage(str(msg))
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/options.py", line 164, in usage
    self.exit(2)
SystemExit: 2
[09/Aug/2017 01:55:26 +0000] 15125 MainThread tmpfs        INFO     Successfully mounted tmpfs at /opt/cm-5.12.0/run/cloudera-scm-agent/process
[09/Aug/2017 01:55:28 +0000] 15125 MainThread agent        INFO     Trying to connect to newly launched supervisor (Attempt 1)
[09/Aug/2017 01:55:28 +0000] 15125 MainThread agent        ERROR    Failed! trying again in 1 second(s)
Traceback (most recent call last):
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.12.0-py2.7.egg/cmf/agent.py", line 2234, in connect_to_new_supervisor
    self.get_supervisor_process_info()
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/cmf-5.12.0-py2.7.egg/cmf/agent.py", line 2254, in get_supervisor_process_info
    self.identifier = self.supervisor_client.supervisor.getIdentification()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/opt/cm-5.12.0/lib64/cmf/agent/build/env/lib/python2.7/site-packages/supervisor-3.0-py2.7.egg/supervisor/xmlrpc.py", line 470, in request
    '' )
ProtocolError: <ProtocolError for 127.0.0.1/RPC2: 401 Unauthorized>
这是后台日志，查了些许资料有说hostname的问题，有说supervisor进程问题，试过后都无法解决

**Comment by mattshma** [comment]
看报错应该是 supervisor 的问题，建议 [google](https://www.google.com.hk/search?safe=strict&q=supervisor+401+Unauthorized&cad=h) 查下 "supervisor 401 Unauthorized"这几个关键字。

**Comment by unasm** [comment]
你好，我遇到这个问题，是因为之前有supervisor的程序未关闭，导致新的 supervisord 无法启动，通过 ps aux | grep supervisor 然后将所有运行的supervisor 程序kill掉即可，good luck
